version: '3.8'
services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: quypq147
      POSTGRES_PASSWORD: quypq147
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:

