version: '3.8'
services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: quypq147
      POSTGRES_PASSWORD: quypq147
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
